# SPDX-FileCopyrightText: 2026 Harmony contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 BoskiYourk <175783845+BoskiYourk@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

### Visitors with Visitor ID

# Security

- type: startingGear
  id: VisitorBrigmedicHarmony
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesBrigmedicHarmony
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatBeretBrigmedic
    id: VisitorPDA
    belt: ClothingBeltBrigmedFilledHarmony
    back: ClothingBackpackBrigmedic
    ears: ClothingHeadsetBrigmedic
    outerClothing: ClothingOuterCoatAMG
    pocket1: WeaponDisabler
    pocket2: ScalpelAdvanced
