# SPDX-FileCopyrightText: 2026 Harmony contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 BoskiYourk <175783845+BoskiYourk@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: BrigMedicHarmony
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigMedicHarmony
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 0 # 0 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0 # 0 hours
  startingGear: BrigMedicGearHarmony
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Medical
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigMedicGearHarmony
  equipment:
    id: BrigmedicPDA
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesBrigmedicHarmony
    gloves: ClothingHandsGlovesNitrile
    ears: ClothingHeadsetBrigmedic
    head: ClothingHeadHatBeretBrigmedic
    outerClothing: ClothingOuterCoatAMG
    belt: ClothingBeltBrigmedFilledHarmony
    back: ClothingBackpackBrigmedic
    pocket1: WeaponDisabler
    pocket2: ScalpelAdvanced
  storage:
    back:
    - Flash
