using System.Linq;
using System.Numerics;
using Content.Client.Paper.UI;
using Content.Client.Stylesheets;
using Content.Shared._SV.CharacterDocuments;
using Content.Shared._SV.CharacterDocuments.Admin;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._SV.CharacterDocuments.Admin;

[GenerateTypedNameReferences]
public sealed partial class AdminCharacterDocumentsTab : Control
{
    public Action<int, CharacterDocument>? OnDocumentEdit;
    public Action<int, int>? OnDocumentDelete;

    private DocumentType _docType;
    private List<AdminSVProfileEntry> _allProfiles = new();
    private string _playerFilter = string.Empty;

    private string? _selectedPlayer;
    private int? _selectedProfileId;
    private CharacterDocument? _selectedDoc;
    private bool _editing;
    private bool _isPopulating;

    public AdminCharacterDocumentsTab()
    {
        RobustXamlLoader.Load(this);

        PlayerFilter.OnTextChanged += args =>
        {
            _playerFilter = args.Text;
            RefreshPlayerListing();
        };

        PlayerListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;
            if (PlayerListing[args.ItemIndex].Metadata is string player)
            {
                _selectedPlayer = player;
                _selectedProfileId = null;
                _selectedDoc = null;
                RefreshCharacterListing();
                RefreshDocumentListing();
                ClearViewer();
            }
        };

        CharacterListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;
            if (CharacterListing[args.ItemIndex].Metadata is int profileId)
            {
                _selectedProfileId = profileId;
                _selectedDoc = null;
                RefreshDocumentListing();
                ClearViewer();
            }
        };

        DocumentListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;
            if (DocumentListing[args.ItemIndex].Metadata is int docId)
            {
                ShowDocument(docId);
            }
        };

        EditButton.OnPressed += _ => OnEditPressed();
        DeleteButton.OnPressed += _ => OnDeletePressed();
    }

    public void Initialize(DocumentType type)
    {
        _docType = type;
    }

    public void SetData(List<AdminSVProfileEntry> profiles)
    {
        // Capture selection BEFORE we reset listings — programmatic Selected=true fires events
        // that would otherwise clobber these (the _isPopulating guard suppresses them).
        var keepPlayer = _selectedPlayer;
        var keepProfile = _selectedProfileId;
        var keepDoc = _selectedDoc?.DocID;

        _isPopulating = true;
        try
        {
            _allProfiles = profiles
                .Where(p => p.Documents.Any(d => d.DocType == (int)_docType))
                .ToList();

            RefreshPlayerListing();

            if (keepPlayer == null || _allProfiles.All(p => p.PlayerName != keepPlayer))
            {
                _selectedPlayer = null;
                _selectedProfileId = null;
                _selectedDoc = null;
                CharacterListing.Clear();
                DocumentListing.Clear();
                ClearViewer();
                return;
            }

            _selectedPlayer = keepPlayer;
            ReselectPlayer(keepPlayer);
            RefreshCharacterListing();

            if (keepProfile is not { } pid || _allProfiles.All(p => p.ProfileId != pid))
            {
                _selectedProfileId = null;
                _selectedDoc = null;
                DocumentListing.Clear();
                ClearViewer();
                return;
            }

            _selectedProfileId = pid;
            ReselectCharacter(pid);
            RefreshDocumentListing();

            if (keepDoc is not { } docId)
            {
                _selectedDoc = null;
                ClearViewer();
                return;
            }

            var entry = _allProfiles.FirstOrDefault(p => p.ProfileId == pid);
            var doc = entry?.Documents.FirstOrDefault(d => d.DocID == docId);
            if (doc == null)
            {
                _selectedDoc = null;
                ClearViewer();
                return;
            }

            ReselectDocument(docId);
            ShowDocument(docId);
        }
        finally
        {
            _isPopulating = false;
        }
    }

    private void RefreshPlayerListing()
    {
        PlayerListing.Clear();
        var seen = new HashSet<string>();
        foreach (var p in _allProfiles.OrderBy(x => x.PlayerName))
        {
            if (!seen.Add(p.PlayerName))
                continue;
            if (!string.IsNullOrEmpty(_playerFilter)
                && !p.PlayerName.Contains(_playerFilter, StringComparison.OrdinalIgnoreCase))
                continue;

            var item = PlayerListing.AddItem(p.PlayerName);
            item.Metadata = p.PlayerName;
        }
    }

    private void ReselectPlayer(string player)
    {
        for (var i = 0; i < PlayerListing.Count; i++)
        {
            if (PlayerListing[i].Metadata is string name && name == player)
            {
                PlayerListing[i].Selected = true;
                return;
            }
        }
    }

    private void RefreshCharacterListing()
    {
        CharacterListing.Clear();
        if (_selectedPlayer == null)
            return;

        foreach (var p in _allProfiles.Where(x => x.PlayerName == _selectedPlayer).OrderBy(x => x.CharacterName))
        {
            var item = CharacterListing.AddItem(p.CharacterName);
            item.Metadata = p.ProfileId;
        }
    }

    private void ReselectCharacter(int profileId)
    {
        for (var i = 0; i < CharacterListing.Count; i++)
        {
            if (CharacterListing[i].Metadata is int pid && pid == profileId)
            {
                CharacterListing[i].Selected = true;
                return;
            }
        }
    }

    private void RefreshDocumentListing()
    {
        DocumentListing.Clear();
        if (_selectedProfileId is not { } pid)
            return;

        var entry = _allProfiles.FirstOrDefault(p => p.ProfileId == pid);
        if (entry == null)
            return;

        foreach (var doc in entry.Documents.Where(d => d.DocType == (int)_docType).OrderBy(d => d.DocTitle))
        {
            var item = DocumentListing.AddItem(doc.DocTitle);
            item.Metadata = doc.DocID;
        }
    }

    private void ReselectDocument(int docId)
    {
        for (var i = 0; i < DocumentListing.Count; i++)
        {
            if (DocumentListing[i].Metadata is int id && id == docId)
            {
                DocumentListing[i].Selected = true;
                ShowDocument(docId);
                return;
            }
        }
    }

    private void ShowDocument(int docId)
    {
        if (_selectedProfileId is not { } pid)
            return;

        var entry = _allProfiles.FirstOrDefault(p => p.ProfileId == pid);
        var doc = entry?.Documents.FirstOrDefault(d => d.DocID == docId);
        if (doc == null)
            return;

        _selectedDoc = doc;
        TitleInput.SetText(doc.DocTitle);
        TitleInput.Editable = false;
        TitleInput.ModulateSelfOverride = null;
        AuthorValue.Text = doc.DocAuthor;
        LastEditedByValue.Text = string.IsNullOrEmpty(doc.DocLastEditedBy) ? doc.DocAuthor : doc.DocLastEditedBy;
        ContentView.Text = doc.DocContent;
        ContentView.Visible = true;
        ContentEdit.TextRope = new Rope.Leaf(doc.DocContent);
        ContentEdit.Visible = false;
        ContentEdit.Editable = false;
        StampDisplay.Visible = true;
        StampDisplay.RemoveStamps();
        StampDisplay.RemoveAllChildren();
        foreach (var stamp in doc.DocStamps)
            StampDisplay.AddStamp(new StampWidget { StampInfo = stamp.DocStamp });

        EditButton.Disabled = false;
        DeleteButton.Disabled = false;
        EditButton.Text = "Edit";
        EditButton.RemoveStyleClass(StyleClass.Negative);
        _editing = false;
    }

    private void ClearViewer()
    {
        _selectedDoc = null;
        TitleInput.Clear();
        TitleInput.Editable = false;
        TitleInput.ModulateSelfOverride = null;
        AuthorValue.Text = string.Empty;
        LastEditedByValue.Text = string.Empty;
        ContentView.Text = string.Empty;
        ContentView.Visible = true;
        ContentEdit.TextRope = Rope.Leaf.Empty;
        ContentEdit.Visible = false;
        ContentEdit.Editable = false;
        StampDisplay.Visible = true;
        StampDisplay.RemoveStamps();
        StampDisplay.RemoveAllChildren();
        EditButton.Disabled = true;
        DeleteButton.Disabled = true;
        EditButton.Text = "Edit";
        EditButton.RemoveStyleClass(StyleClass.Negative);
        _editing = false;
    }

    private void OnEditPressed()
    {
        if (_selectedDoc == null || _selectedProfileId is not { } pid)
            return;

        if (!_editing)
        {
            _editing = true;
            ContentView.Visible = false;
            StampDisplay.Visible = false;
            ContentEdit.Visible = true;
            ContentEdit.Editable = true;
            TitleInput.Editable = true;
            TitleInput.ModulateSelfOverride = Color.FromHex("#ff6666");
            EditButton.Text = "Save";
            EditButton.AddStyleClass(StyleClass.Negative);
            DeleteButton.Disabled = true;
        }
        else
        {
            if (ContentEdit.TextRope == null)
                return;

            var newContent = Rope.Collapse(ContentEdit.TextRope);
            if (string.IsNullOrEmpty(newContent))
                return;

            var updated = new CharacterDocument
            {
                DocID = _selectedDoc.DocID,
                DocType = _selectedDoc.DocType,
                DocTitle = TitleInput.Text,
                DocAuthor = _selectedDoc.DocAuthor,
                DocLastEditedBy = _selectedDoc.DocLastEditedBy,
                DocDateLastEdited = _selectedDoc.DocDateLastEdited,
                DocContent = newContent,
                DocStamps = _selectedDoc.DocStamps,
            };

            _editing = false;
            ContentEdit.Editable = false;
            ContentEdit.Visible = false;
            ContentView.Visible = true;
            StampDisplay.Visible = true;
            TitleInput.Editable = false;
            TitleInput.ModulateSelfOverride = null;
            EditButton.Text = "Edit";
            EditButton.RemoveStyleClass(StyleClass.Negative);
            DeleteButton.Disabled = false;

            if (updated.DocTitle == _selectedDoc.DocTitle && newContent == _selectedDoc.DocContent)
                return;

            OnDocumentEdit?.Invoke(pid, updated);
        }
    }

    private void OnDeletePressed()
    {
        if (_selectedDoc == null || _selectedProfileId is not { } pid)
            return;

        OnDocumentDelete?.Invoke(pid, _selectedDoc.DocID);
        _selectedDoc = null;
        ClearViewer();
    }
}
