// SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._SV.CharacterDocuments;
using Content.Shared._SV.CharacterDocuments.Admin;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SV.CharacterDocuments.Admin;

[GenerateTypedNameReferences]
public sealed partial class AdminCharacterDocumentsWindow : DefaultWindow
{
    private static readonly DocumentType[] TypesInOrder =
    [
        DocumentType.Employment,
        DocumentType.Medical,
        DocumentType.Security,
        DocumentType.CentralCommand,
        DocumentType.Syndicate,
        DocumentType.Admin,
    ];

    private readonly Dictionary<DocumentType, AdminCharacterDocumentsTab> _tabs = new();

    public Action? OnRefresh;
    public Action<int, CharacterDocument>? OnEdit;
    public Action<int, int>? OnDelete;
    public Action<int, int>? OnRestore;
    public Action<int, int>? OnPurge;
    public Action<int>? OnEmptyBin;
    public Action<int, DocumentType, string, string, List<CharacterDocumentStamp>>? OnCreate;

    public AdminCharacterDocumentsWindow()
    {
        RobustXamlLoader.Load(this);

        for (var i = 0; i < TypesInOrder.Length; i++)
        {
            var type = TypesInOrder[i];
            var tab = new AdminCharacterDocumentsTab();
            tab.Initialize(type);
            tab.OnDocumentEdit = (pid, doc) => OnEdit?.Invoke(pid, doc);
            tab.OnDocumentDelete = (pid, did) => OnDelete?.Invoke(pid, did);
            tab.OnDocumentRestore = (pid, did) => OnRestore?.Invoke(pid, did);
            tab.OnDocumentPurge = (pid, did) => OnPurge?.Invoke(pid, did);
            tab.OnDocumentEmptyBin = pid => OnEmptyBin?.Invoke(pid);
            tab.OnDocumentCreate = (pid, t, title, content, stamps) => OnCreate?.Invoke(pid, t, title, content, stamps);
            TypeTabs.AddChild(tab);
            TypeTabs.SetTabTitle(i, type.ToString());
            _tabs[type] = tab;
        }

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void SetData(List<AdminSVProfileEntry> profiles)
    {
        foreach (var (_, tab) in _tabs)
            tab.SetData(profiles);

        var charCount = 0;
        var docCount = 0;
        foreach (var p in profiles)
        {
            charCount++;
            docCount += p.Documents.Count;
        }
        StatusLabel.Text = $"{charCount} characters / {docCount} documents";
    }
}
