// SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Paper.UI;
using Content.Client.Stylesheets;
using Content.Shared._SV.CharacterDocuments;
using Content.Shared._SV.CharacterDocuments.Admin;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._SV.CharacterDocuments.Admin;

[GenerateTypedNameReferences]
public sealed partial class AdminCharacterDocumentsTab : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<int, CharacterDocument>? OnDocumentEdit;
    public Action<int, int>? OnDocumentDelete;
    public Action<int, DocumentType, string, string, List<CharacterDocumentStamp>>? OnDocumentCreate;

    private DocumentType _docType;
    private List<AdminSVProfileEntry> _allProfiles = new();
    private string _playerFilter = string.Empty;

    private string? _selectedPlayer;
    private int? _selectedProfileId;
    private CharacterDocument? _selectedDoc;
    private bool _editing;
    private bool _creating;
    private bool _isPopulating;

    // Stamps currently being assembled while editing or creating.
    private readonly List<CharacterDocumentStamp> _stampDraft = new();
    // (prototypeId, stampDisplayInfo, stampState) tuples indexed by OptionButton id.
    private readonly List<(string Proto, StampDisplayInfo Info, string State)> _stampOptions = new();

    public AdminCharacterDocumentsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateStampPicker();

        PlayerFilter.OnTextChanged += args =>
        {
            _playerFilter = args.Text;
            RefreshPlayerListing();
        };

        PlayerListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;
            if (PlayerListing[args.ItemIndex].Metadata is string player)
            {
                _selectedPlayer = player;
                _selectedProfileId = null;
                _selectedDoc = null;
                RefreshCharacterListing();
                RefreshDocumentListing();
                ClearViewer();
                CreateButton.Disabled = true;
            }
        };

        CharacterListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;
            if (CharacterListing[args.ItemIndex].Metadata is int profileId)
            {
                _selectedProfileId = profileId;
                _selectedDoc = null;
                RefreshDocumentListing();
                ClearViewer();
                CreateButton.Disabled = false;
            }
        };

        DocumentListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;
            if (DocumentListing[args.ItemIndex].Metadata is int docId)
            {
                ShowDocument(docId);
            }
        };

        EditButton.OnPressed += _ => OnEditPressed();
        DeleteButton.OnPressed += _ => OnDeletePressed();
        CreateButton.OnPressed += _ => OnCreatePressed();
        StampPicker.OnItemSelected += args => StampPicker.SelectId(args.Id);
        AddStampButton.OnPressed += _ => OnAddStampPressed();
        ClearStampsButton.OnPressed += _ => OnClearStampsPressed();
    }

    private void PopulateStampPicker()
    {
        _stampOptions.Clear();
        StampPicker.Clear();

        // Build a sorted list of entity prototypes that carry a StampComponent.
        // We use the prototype's component data to derive the display info
        // since stamps are never instantiated as actual entities here.
        var options = _proto.EnumeratePrototypes<EntityPrototype>()
            .Where(p => p.Components.ContainsKey("Stamp"))
            .OrderBy(p => p.Name)
            .ToList();

        var id = 0;
        foreach (var proto in options)
        {
            if (!proto.TryGetComponent<StampComponent>(out var stamp))
                continue;

            var info = new StampDisplayInfo
            {
                StampedName = stamp.StampedName,
                StampedColor = stamp.StampedColor,
                Type = StampType.RubberStamp,
            };

            _stampOptions.Add((proto.ID, info, stamp.StampState));
            StampPicker.AddItem(proto.Name, id);
            id++;
        }

        if (id > 0)
            StampPicker.SelectId(0);
    }

    private void OnCreatePressed()
    {
        if (_selectedProfileId is not { } pid)
            return;

        _creating = true;
        _editing = false;
        _selectedDoc = null;
        _stampDraft.Clear();

        // Deselect any document; we're authoring a fresh one.
        for (var i = 0; i < DocumentListing.Count; i++)
            DocumentListing[i].Selected = false;

        TitleInput.Clear();
        TitleInput.SetText(string.Empty);
        TitleInput.Editable = true;
        TitleInput.ModulateSelfOverride = Color.FromHex("#ff6666");

        AuthorValue.Text = "Central Command";
        LastEditedByValue.Text = "Central Command";

        ContentView.Visible = false;
        StampDisplay.Visible = false;
        ContentEdit.TextRope = Rope.Leaf.Empty;
        ContentEdit.Visible = true;
        ContentEdit.Editable = true;

        StampEditorRow.Visible = true;

        EditButton.Text = Loc.GetString("sv-document-console-edit-button-save");
        EditButton.AddStyleClass(StyleClass.Negative);
        EditButton.Disabled = false;
        DeleteButton.Disabled = true;
        CreateButton.Disabled = true;
    }

    private void OnAddStampPressed()
    {
        if (StampPicker.SelectedId < 0 || StampPicker.SelectedId >= _stampOptions.Count)
            return;
        if (!_editing && !_creating)
            return;

        var (_, info, state) = _stampOptions[StampPicker.SelectedId];
        _stampDraft.Add(new CharacterDocumentStamp { DocStamp = info, DocStampState = state });
        RefreshStampDraftDisplay();
    }

    private void OnClearStampsPressed()
    {
        if (!_editing && !_creating)
            return;

        _stampDraft.Clear();
        RefreshStampDraftDisplay();
    }

    private void RefreshStampDraftDisplay()
    {
        StampDisplay.RemoveStamps();
        StampDisplay.RemoveAllChildren();
        StampDisplay.Visible = true;
        foreach (var stamp in _stampDraft)
            StampDisplay.AddStamp(new StampWidget { StampInfo = stamp.DocStamp });
    }

    public void Initialize(DocumentType type)
    {
        _docType = type;
    }

    public void SetData(List<AdminSVProfileEntry> profiles)
    {
        // Capture selection BEFORE we reset listings — programmatic Selected=true fires events
        // that would otherwise clobber these (the _isPopulating guard suppresses them).
        var keepPlayer = _selectedPlayer;
        var keepProfile = _selectedProfileId;
        var keepDoc = _selectedDoc?.DocID;

        _isPopulating = true;
        try
        {
            // Show every profile in every tab so admins can create new docs of any
            // type. The per-tab type filter is applied at the document-list level.
            _allProfiles = profiles;

            RefreshPlayerListing();

            if (keepPlayer == null || _allProfiles.All(p => p.PlayerName != keepPlayer))
            {
                _selectedPlayer = null;
                _selectedProfileId = null;
                _selectedDoc = null;
                CharacterListing.Clear();
                DocumentListing.Clear();
                ClearViewer();
                return;
            }

            _selectedPlayer = keepPlayer;
            ReselectPlayer(keepPlayer);
            RefreshCharacterListing();

            if (keepProfile is not { } pid || _allProfiles.All(p => p.ProfileId != pid))
            {
                _selectedProfileId = null;
                _selectedDoc = null;
                DocumentListing.Clear();
                ClearViewer();
                return;
            }

            _selectedProfileId = pid;
            ReselectCharacter(pid);
            RefreshDocumentListing();

            if (keepDoc is not { } docId)
            {
                _selectedDoc = null;
                ClearViewer();
                return;
            }

            var entry = _allProfiles.FirstOrDefault(p => p.ProfileId == pid);
            var doc = entry?.Documents.FirstOrDefault(d => d.DocID == docId);
            if (doc == null)
            {
                _selectedDoc = null;
                ClearViewer();
                return;
            }

            ReselectDocument(docId);
            ShowDocument(docId);
        }
        finally
        {
            _isPopulating = false;
        }
    }

    private void RefreshPlayerListing()
    {
        PlayerListing.Clear();
        var seen = new HashSet<string>();
        foreach (var p in _allProfiles.OrderBy(x => x.PlayerName))
        {
            if (!seen.Add(p.PlayerName))
                continue;
            if (!string.IsNullOrEmpty(_playerFilter)
                && !p.PlayerName.Contains(_playerFilter, StringComparison.OrdinalIgnoreCase))
                continue;

            var item = PlayerListing.AddItem(p.PlayerName);
            item.Metadata = p.PlayerName;
        }
    }

    private void ReselectPlayer(string player)
    {
        for (var i = 0; i < PlayerListing.Count; i++)
        {
            if (PlayerListing[i].Metadata is string name && name == player)
            {
                PlayerListing[i].Selected = true;
                return;
            }
        }
    }

    private void RefreshCharacterListing()
    {
        CharacterListing.Clear();
        if (_selectedPlayer == null)
            return;

        foreach (var p in _allProfiles.Where(x => x.PlayerName == _selectedPlayer).OrderBy(x => x.CharacterName))
        {
            var item = CharacterListing.AddItem(p.CharacterName);
            item.Metadata = p.ProfileId;
        }
    }

    private void ReselectCharacter(int profileId)
    {
        for (var i = 0; i < CharacterListing.Count; i++)
        {
            if (CharacterListing[i].Metadata is int pid && pid == profileId)
            {
                CharacterListing[i].Selected = true;
                return;
            }
        }
    }

    private void RefreshDocumentListing()
    {
        DocumentListing.Clear();
        if (_selectedProfileId is not { } pid)
            return;

        var entry = _allProfiles.FirstOrDefault(p => p.ProfileId == pid);
        if (entry == null)
            return;

        foreach (var doc in entry.Documents.Where(d => d.DocType == (int)_docType).OrderBy(d => d.DocTitle))
        {
            var item = DocumentListing.AddItem(doc.DocTitle);
            item.Metadata = doc.DocID;
        }
    }

    private void ReselectDocument(int docId)
    {
        for (var i = 0; i < DocumentListing.Count; i++)
        {
            if (DocumentListing[i].Metadata is int id && id == docId)
            {
                DocumentListing[i].Selected = true;
                ShowDocument(docId);
                return;
            }
        }
    }

    private void ShowDocument(int docId)
    {
        if (_selectedProfileId is not { } pid)
            return;

        var entry = _allProfiles.FirstOrDefault(p => p.ProfileId == pid);
        var doc = entry?.Documents.FirstOrDefault(d => d.DocID == docId);
        if (doc == null)
            return;

        _selectedDoc = doc;
        TitleInput.SetText(doc.DocTitle);
        TitleInput.Editable = false;
        TitleInput.ModulateSelfOverride = null;
        AuthorValue.Text = doc.DocAuthor;
        LastEditedByValue.Text = string.IsNullOrEmpty(doc.DocLastEditedBy) ? doc.DocAuthor : doc.DocLastEditedBy;
        ContentView.Text = doc.DocContent;
        ContentView.Visible = true;
        ContentEdit.TextRope = new Rope.Leaf(doc.DocContent);
        ContentEdit.Visible = false;
        ContentEdit.Editable = false;
        StampDisplay.Visible = true;
        StampDisplay.RemoveStamps();
        StampDisplay.RemoveAllChildren();
        foreach (var stamp in doc.DocStamps)
            StampDisplay.AddStamp(new StampWidget { StampInfo = stamp.DocStamp });

        EditButton.Disabled = false;
        DeleteButton.Disabled = false;
        EditButton.Text = Loc.GetString("sv-document-console-edit-button");
        EditButton.RemoveStyleClass(StyleClass.Negative);
        _editing = false;
    }

    private void ClearViewer()
    {
        _selectedDoc = null;
        TitleInput.Clear();
        TitleInput.Editable = false;
        TitleInput.ModulateSelfOverride = null;
        AuthorValue.Text = string.Empty;
        LastEditedByValue.Text = string.Empty;
        ContentView.Text = string.Empty;
        ContentView.Visible = true;
        ContentEdit.TextRope = Rope.Leaf.Empty;
        ContentEdit.Visible = false;
        ContentEdit.Editable = false;
        StampDisplay.Visible = true;
        StampDisplay.RemoveStamps();
        StampDisplay.RemoveAllChildren();
        EditButton.Disabled = true;
        DeleteButton.Disabled = true;
        EditButton.Text = Loc.GetString("sv-document-console-edit-button");
        EditButton.RemoveStyleClass(StyleClass.Negative);
        _editing = false;
    }

    private void OnEditPressed()
    {
        if (_selectedProfileId is not { } pid)
            return;

        // === Save path for "Create" mode ===
        if (_creating)
        {
            if (ContentEdit.TextRope == null)
                return;

            var newContent = Rope.Collapse(ContentEdit.TextRope);
            var title = string.IsNullOrWhiteSpace(TitleInput.Text) ? "Untitled" : TitleInput.Text;

            OnDocumentCreate?.Invoke(pid, _docType, title, newContent, new List<CharacterDocumentStamp>(_stampDraft));

            _creating = false;
            _stampDraft.Clear();
            StampEditorRow.Visible = false;
            // ClearViewer will reset UI; new state arrives via ReloadAsync round-trip.
            ClearViewer();
            CreateButton.Disabled = _selectedProfileId == null;
            return;
        }

        // === Edit mode requires an existing selection ===
        if (_selectedDoc == null)
            return;

        if (!_editing)
        {
            _editing = true;
            _stampDraft.Clear();
            _stampDraft.AddRange(_selectedDoc.DocStamps);

            ContentView.Visible = false;
            ContentEdit.Visible = true;
            ContentEdit.Editable = true;
            TitleInput.Editable = true;
            TitleInput.ModulateSelfOverride = Color.FromHex("#ff6666");
            EditButton.Text = Loc.GetString("sv-document-console-edit-button-save");
            EditButton.AddStyleClass(StyleClass.Negative);
            DeleteButton.Disabled = true;
            CreateButton.Disabled = true;

            StampEditorRow.Visible = true;
            RefreshStampDraftDisplay();
        }
        else
        {
            if (ContentEdit.TextRope == null)
                return;

            var newContent = Rope.Collapse(ContentEdit.TextRope);
            if (string.IsNullOrEmpty(newContent))
                return;

            var updated = new CharacterDocument
            {
                DocID = _selectedDoc.DocID,
                DocType = _selectedDoc.DocType,
                DocTitle = TitleInput.Text,
                DocAuthor = _selectedDoc.DocAuthor,
                DocLastEditedBy = _selectedDoc.DocLastEditedBy,
                DocDateLastEdited = _selectedDoc.DocDateLastEdited,
                DocContent = newContent,
                DocStamps = new List<CharacterDocumentStamp>(_stampDraft),
            };

            _editing = false;
            _stampDraft.Clear();
            StampEditorRow.Visible = false;
            ContentEdit.Editable = false;
            ContentEdit.Visible = false;
            ContentView.Visible = true;
            StampDisplay.Visible = true;
            TitleInput.Editable = false;
            TitleInput.ModulateSelfOverride = null;
            EditButton.Text = Loc.GetString("sv-document-console-edit-button");
            EditButton.RemoveStyleClass(StyleClass.Negative);
            DeleteButton.Disabled = false;
            CreateButton.Disabled = false;

            // Only send if anything actually changed.
            var stampsChanged = !StampsEqual(updated.DocStamps, _selectedDoc.DocStamps);
            if (!stampsChanged
                && updated.DocTitle == _selectedDoc.DocTitle
                && newContent == _selectedDoc.DocContent)
                return;

            OnDocumentEdit?.Invoke(pid, updated);
        }
    }

    private static bool StampsEqual(List<CharacterDocumentStamp> a, List<CharacterDocumentStamp> b)
    {
        if (a.Count != b.Count)
            return false;
        for (var i = 0; i < a.Count; i++)
        {
            if (a[i].DocStampState != b[i].DocStampState)
                return false;
            if (a[i].DocStamp.StampedName != b[i].DocStamp.StampedName)
                return false;
        }
        return true;
    }

    private void OnDeletePressed()
    {
        if (_selectedDoc == null || _selectedProfileId is not { } pid)
            return;

        OnDocumentDelete?.Invoke(pid, _selectedDoc.DocID);
        _selectedDoc = null;
        ClearViewer();
    }
}
