# SPDX-FileCopyrightText: 2026 Harmony contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: loadout
  id: HeadofSecurityAssaultSuit # Harmony Change: Updated ID for HoS Clothing and Loadout Update. Old ID: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityAssaultSkirt # Harmony Change: Updated ID for HoS Clothing and Loadout Update. Old ID: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt
  groupBy: "jumpskirt"
