# SPDX-FileCopyrightText: 2026 Cosmatic Drift contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: MIT

- type: playTimeTracker
  id: JobPrisoner
#Check this out later SV - Rebound

- type: playTimeTracker
  id: JobPrivateInvestigator

# Senior Roles
- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher
