# SPDX-FileCopyrightText: 2026 Harmony contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Spanky <scott@wearejacob.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Harmony CC character presets

- type: startingGear
  id: CentcomOfficialGearHarmony
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlassesCommand
    neck: ClothingNeckCloakCentcom
    gloves: WristwatchGold
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: BoxFolderCentComClipboard
    pocket1: WeaponPistolN1984
    pocket2: MagazineMagnum
  inhand:
    - MindShieldImplanter

- type: startingGear
  id: CentcomAgentGearHarmony
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAgent
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: WristwatchGold
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPulsePistol
    pocket1: BoxFolderCentComClipboard
    pocket2: RubberStampCentcom
  inhand:
    - MindShieldImplanter