// SPDX-FileCopyrightText: 2026 AXOLOTL contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._AXOLOTL.RespawnButton;

[GenerateTypedNameReferences]
public sealed partial class GhostRespawnRulesWindow : FancyWindow
{
    public PanelContainer RulesContainer => TextContainer;
    public RichTextLabel RulesLabel = new() { Margin = new Thickness(5, 5, 5, 5) };
    public Button RespawnButton => ConfirmRespawnButton;

    public GhostRespawnRulesWindow()
    {
        RobustXamlLoader.Load(this);

        var message = new FormattedMessage();
        message.AddMarkup(Loc.GetString("ghost-respawn-rules-window-rules"));
        RulesLabel.SetMessage(message);
        RulesContainer.AddChild(RulesLabel);
        RulesLabel.SetPositionFirst();

        RespawnButton.OnPressed += _ => Close();
    }
}
