# SPDX-FileCopyrightText: 2026 Cosmatic Drift contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  setPreference: true
  whitelisted: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience

- type: chameleonOutfit
  id: SeniorResearcherChameleonOutfit
  job: SeniorResearcher
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
