using Content.Client.RichText;
using Content.Shared._SV.CharacterDocuments;
using Content.Shared._SV.CharacterDocuments.Consoles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._SV.CharacterDocuments.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDocumentConsoleWindow : DefaultWindow
{
    public CharacterDocumentConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        CrewListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;

            if (CrewListing[args.ItemIndex].Metadata is not NetEntity uid)
                return;

            OnPlayerSelected?.Invoke(uid);
        };

        DocumentListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;

            if (DocumentListing[args.ItemIndex].Metadata is not int uid)
                return;

            OnDocumentSelected?.Invoke(_selectedPlayer, uid);
        };
    }

    public void UpdateState(CharacterDocumentConsoleState state)
    {
        _isPopulating = true;
        CrewListing.Clear();

        if (state.SelectedPlayer.HasValue)
            _selectedPlayer = state.SelectedPlayer.Value;

        foreach (var (uid, name) in state.PlayerList)
        {
            var item = CrewListing.AddItem(name);
            item.Metadata = uid;
        }
        _isPopulating = false;

        if (state.SelectedPlayerDocuments == null)
        {
            DocumentListingStatus.Visible = false;
            DocumentListing.Visible = true;
        }
        else
        {
            _isPopulating = true;
            DocumentListing.Clear();
            foreach (var doc in state.SelectedPlayerDocuments.Values)
            {
                DocumentListing.AddItem(doc.DocTitle, null, true, doc.DocID);
            }
            DocumentListingStatus.Visible = false;
            DocumentListing.Visible = true;
            _isPopulating = false;
        }

        if (state.SelectedDocument == null)
        {
            Document.Clear();
        }
        else
        {
            Document.SetMessage(FormattedMessage.FromMarkupPermissive(state.SelectedDocument.DocContent), UserFormattableTags.BaseAllowedTags);
        }
    }

    private NetEntity _selectedPlayer;
    public Action<NetEntity>? OnPlayerSelected;
    public Action<NetEntity, int>? OnDocumentSelected;
    bool _isPopulating;
}
