using Content.Client.RichText;
using Content.Shared._SV.CharacterDocuments;
using Content.Shared._SV.CharacterDocuments.Consoles;
using Content.Shared.Security;
using Content.Client._SV.CharacterDocuments.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.State;
using System.Linq;
using Content.Client.Paper.UI;
using Content.Shared.Paper;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface.Controls;
using System.Numerics;

namespace Content.Client._SV.CharacterDocuments.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDocumentConsoleWindow : DefaultWindow
{
    public CharacterDocumentConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        CrewListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;

            if (CrewListing[args.ItemIndex].Metadata is not NetEntity uid)
                return;

            OnPlayerSelected?.Invoke(uid);
        };

        CrewListing.OnItemDeselected += args =>
        {
            if (_isPopulating)
                return;

            DocumentListing.Clear();
            Document.Clear();
            DocumentEdit.TextRope = Rope.Leaf.Empty;
            StampDisplay.RemoveStamps();
            StampDisplay.RemoveAllChildren();
        };

        CrewFiltersValue.OnTextChanged += args =>
        {
            _isPopulating = true;
            CrewListing.Clear();
            foreach (var (uid, name) in _cachedPlayerList.OrderBy(x => x.Value))
            {
                if (name.Contains(args.Text, StringComparison.OrdinalIgnoreCase))
                {
                    var item = CrewListing.AddItem(name);
                    item.Metadata = uid;
                }
            }
            _isPopulating = false;
        };

        DocumentListing.OnItemSelected += args =>
        {
            if (_isPopulating)
                return;

            if (DocumentListing[args.ItemIndex].Metadata is not int uid)
                return;

            OnDocumentSelected?.Invoke(_selectedPlayer, uid);
        };

        DocumentListing.OnItemDeselected += args =>
        {
            if (_isPopulating)
                return;

            OnDocumentDeselected?.Invoke();
            Document.Clear();
            DocumentEdit.TextRope = Rope.Leaf.Empty;
            StampDisplay.RemoveStamps();
            StampDisplay.RemoveAllChildren();
        };

        ScanButton.OnPressed += _ =>
        {
            var popup = new CharacterDocumentTitlePopup();
            // Pass the active tab's DocumentType so scans on a multi-type console land
            // in the tab the user is viewing rather than always the primary type.
            popup.OnConfirmed += title => OnButtonScanPressed?.Invoke(_selectedPlayer, title, _activeTypeFilter);
            popup.OpenCentered();
        };

        DeleteButton.OnPressed += _ =>
        {
            if (_selectedDocument == null) return;

            if (!_confirmingDelete)
            {
                _confirmingDelete = true;
                DeleteButton.Text = Loc.GetString("sv-document-console-delete-button-confirm");
                DeleteButton.AddStyleClass(StyleClass.Negative);
            }
            else
            {
                _confirmingDelete = false;
                DeleteButton.Disabled = true;
                DeleteButton.Text = Loc.GetString("sv-document-console-delete-button");
                DeleteButton.RemoveStyleClass(StyleClass.Negative);
                OnButtonDeletePressed?.Invoke(_selectedPlayer, _selectedDocument);
            }
        };

        PrintButton.OnPressed += _ =>
        {
            if (_selectedDocument == null) return;
            OnButtonPrintPressed?.Invoke(_selectedPlayer, _selectedDocument);
        };

        EditButton.OnPressed += _ =>
        {
            if (_selectedDocument == null) return;

            if (!_editing)
            {
                _editing = true;
                Document.Visible = false;
                DocumentEdit.Visible = true;
                DocumentEdit.Editable = true;
                StampDisplay.Visible = false;
                TitleInput.Editable = true;
                TitleInput.ModulateSelfOverride = Color.FromHex("#ff6666");
                PrintButton.Disabled = true;
                ScanButton.Disabled = true;
                DeleteButton.Disabled = true;
                EditButton.Text = Loc.GetString("sv-document-console-edit-button-save");
                EditButton.AddStyleClass(StyleClass.Negative);

            }
            else
            {
                if (DocumentEdit.TextRope == null)
                    return;

                string newDocContent = Rope.Collapse(DocumentEdit.TextRope);

                if (string.IsNullOrEmpty(newDocContent))
                    return;

                CharacterDocument newDocument = new()
                {
                    DocID = _selectedDocument.DocID,
                    DocTitle = TitleInput.Text,
                    DocAuthor = _selectedDocument.DocAuthor,
                    DocContent = newDocContent,
                    DocStamps = _selectedDocument.DocStamps,
                    DocType = _selectedDocument.DocType,
                };

                DocumentEdit.Editable = false;
                DocumentEdit.Visible = false;
                _editing = false;
                Document.Visible = true;
                StampDisplay.Visible = true;
                TitleInput.Editable = false;
                TitleInput.ModulateSelfOverride = null;
                PrintButton.Disabled = false;
                DeleteButton.Disabled = _selectedDocument == null;
                EditButton.RemoveStyleClass(StyleClass.Negative);
                EditButton.Text = Loc.GetString("sv-document-console-edit-button");

                if (newDocument.DocTitle == _selectedDocument?.DocTitle && newDocContent == _selectedDocument.DocContent)
                    return;

                // Reflect the edit locally right away so the reader pane shows the new
                // copy without waiting for the server state round-trip (which can be
                // delayed or, on a failed preferences refresh, never arrive).
                Document.Text = newDocContent;
                _selectedDocument = newDocument;

                EditButton.Disabled = true;
                OnButtonEditPressed?.Invoke(_selectedPlayer, newDocument);
            }
        };

        StatusButton.OnPressed += _ =>
        {
            OnStatusButtonPressed?.Invoke(_selectedPlayer);
        };
    }

    public void UpdateState(CharacterDocumentConsoleState state)
    {
        // Title reflects the console's primary DocumentType. Multi-type consoles
        // (e.g. CentComm) keep their primary title even when the user clicks a
        // different tab — the tab itself communicates the active filter.
        Title = state.DocumentType switch
        {
            DocumentType.Employment => Loc.GetString("sv-document-console-window-title-employment"),
            DocumentType.Medical => Loc.GetString("sv-document-console-window-title-medical"),
            DocumentType.Security => Loc.GetString("sv-document-console-window-title-security"),
            DocumentType.CentralCommand => Loc.GetString("sv-document-console-window-title-centralcommand"),
            DocumentType.Syndicate => Loc.GetString("sv-document-console-window-title-syndicate"),
            DocumentType.Admin => Loc.GetString("sv-document-console-window-title-admin"),
            _ => Loc.GetString("sv-document-console-window-title-fallback"),
        };

        _isPopulating = true;
        CrewListing.Clear();
        DocumentListing.Clear();
        DocumentScrollContainer.SetScrollValue(new Vector2(0, 0));
        _cachedPlayerList = state.PlayerList;
        ScanButton.Disabled = !state.SelectedPlayer.HasValue || state.PaperInserted == false;
        PaperStatusLabel.Text = Loc.GetString(state.PaperInserted
            ? "sv-document-console-paper-inserted"
            : "sv-document-console-paper-empty");
        PaperStatusLabel.FontColorOverride = Color.White;
        PaperStatusPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = state.PaperInserted ? Color.FromHex("#2e7d32") : Color.FromHex("#5a2222"),
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };
        PrintButton.Disabled = state.SelectedDocument == null;
        DeleteButton.Disabled = state.SelectedDocument == null;
        EditButton.Disabled = state.SelectedDocument == null;

        var isSecurity = state.DocumentType == DocumentType.Security;
        var hasPlayer = state.SelectedPlayer.HasValue;
        StatusButton.Visible = isSecurity;
        StatusButton.Disabled = !hasPlayer;
        DocSecurityStatusLabel.Visible = isSecurity;
        DocSecurityStatusLabelValue.Visible = isSecurity;
        DocSecurityReasonLabel.Visible = isSecurity;
        DocSecurityReasonLabelValue.Visible = isSecurity;

        if (isSecurity && hasPlayer)
        {
            DocSecurityStatusLabelValue.Text = state.SecurityStatus.ToString();
            DocSecurityReasonLabelValue.Text = state.SecurityReason ?? Loc.GetString("sv-document-console-security-na");
        }
        else
        {
            DocSecurityStatusLabelValue.Text = Loc.GetString("sv-document-console-security-none");
            DocSecurityReasonLabelValue.Text = Loc.GetString("sv-document-console-security-na");
        }

        foreach (var (uid, name) in state.PlayerList.OrderBy(x => x.Value))
        {
            var item = CrewListing.AddItem(name);
            item.Metadata = uid;
        }

        if (state.SelectedPlayer.HasValue)
        {
            _selectedPlayer = state.SelectedPlayer.Value;
            for (var i = 0; i < CrewListing.Count; i++)
            {
                if (CrewListing[i].Metadata is NetEntity uid && uid == state.SelectedPlayer.Value)
                {
                    CrewListing[i].Selected = true;
                    break;
                }
            }
        }

        _isPopulating = false;

        // Build the per-type tab strip when the console has additional doc types
        // (e.g. Central Command). Single-type consoles keep it hidden.
        RebuildDocumentTabs(state);

        _cachedDocuments = state.SelectedPlayerDocuments;
        _lastSelectedDoc = state.SelectedDocument;
        _cachedGeneral = state.SelectedPlayerGeneral;
        _consolePrimaryType = state.DocumentType;
        RefreshGeneralFields();

        if (state.SelectedPlayerDocuments == null)
        {
            DocumentListingStatus.Visible = false;
            DocumentListing.Visible = true;
        }
        else
        {
            PopulateDocumentListing();
        }

        if (state.SelectedDocument == null)
        {
            _selectedDocument = null;
            DocumentEdit.TextRope = Rope.Leaf.Empty;
            Document.Clear();
            TitleInput.Clear();
            StampDisplay.RemoveStamps();
            StampDisplay.RemoveAllChildren();
            DocAuthorLabelValue.Text = Loc.GetString("sv-document-console-author-label-value-none");
            DocLastEditedByLabelValue.Text = Loc.GetString("sv-document-console-editedby-label-value-none");
            DocDateLabelValue.Text = Loc.GetString("sv-document-console-date-label-value-none");
        }
        else
        {
            _selectedDocument = state.SelectedDocument;
            Document.Text = state.SelectedDocument.DocContent;
            DocumentEdit.TextRope = new Rope.Leaf(state.SelectedDocument.DocContent);
            DocAuthorLabelValue.Text = Loc.GetString("sv-document-console-author-label-value", ("DocAuthor", state.SelectedDocument.DocAuthor));
            DocLastEditedByLabelValue.Text = Loc.GetString("sv-document-console-editedby-label-value", ("DocLastEditedBy", string.IsNullOrEmpty(state.SelectedDocument.DocLastEditedBy) ? state.SelectedDocument.DocAuthor : state.SelectedDocument.DocLastEditedBy));
            DocDateLabelValue.Text = Loc.GetString("sv-document-console-date-label-value", ("DocDateLastEdited", state.SelectedDocument.DocDateLastEdited.ToString("yyyy-MM-dd")));
            TitleInput.Clear();
            TitleInput.SetText(state.SelectedDocument.DocTitle);
            StampDisplay.RemoveStamps();
            StampDisplay.RemoveAllChildren();
            if (state.SelectedDocument.DocStamps.Count != 0)
                foreach (CharacterDocumentStamp stamp in state.SelectedDocument.DocStamps)
                {
                    StampDisplay.AddStamp(new StampWidget { StampInfo = stamp.DocStamp });
                }
        }
    }

    private void RebuildDocumentTabs(CharacterDocumentConsoleState state)
    {
        // Single-type consoles: hide the strip entirely and clear filter so all docs (1 type) show.
        if (state.AdditionalDocumentTypes.Count == 0)
        {
            DocumentTypeTabs.Visible = false;
            DocumentTypeTabs.RemoveAllChildren();
            _activeTypeFilter = null;
            return;
        }

        // Default to the primary type if nothing's selected yet, or if the selection
        // no longer belongs to this console (e.g. console reused with different types).
        var allTypes = new List<DocumentType> { state.DocumentType };
        allTypes.AddRange(state.AdditionalDocumentTypes);
        if (_activeTypeFilter == null || !allTypes.Contains(_activeTypeFilter.Value))
            _activeTypeFilter = state.DocumentType;

        DocumentTypeTabs.RemoveAllChildren();
        DocumentTypeTabs.Visible = true;
        foreach (var type in allTypes)
        {
            var btn = new Button
            {
                Text = type.ToString(),
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = type == _activeTypeFilter,
            };
            // Local copy so the closure binds to the right value.
            var localType = type;
            btn.OnPressed += _ =>
            {
                _activeTypeFilter = localType;
                // Re-render every tab to update pressed states.
                foreach (var child in DocumentTypeTabs.Children)
                    if (child is Button b)
                        b.Pressed = b.Text == localType.ToString();
                PopulateDocumentListing();
                RefreshGeneralFields();
            };
            DocumentTypeTabs.AddChild(btn);
        }
    }

    /// <summary>
    ///     Show / hide General flavour fields (height, allergies, etc) based on the active
    ///     tab type. Per-type mapping: each in-world console only shows the fields that
    ///     match its purpose so a Security console doesn't display drug allergies, etc.
    /// </summary>
    private void RefreshGeneralFields()
    {
        var activeType = _activeTypeFilter ?? _consolePrimaryType;
        var g = _cachedGeneral;

        // Per-type rules. Medical is the broadest (it's the "body / wellness" tab);
        // Security gets only stuff useful for ID; Employment gets work auth.
        // Visibility is driven purely by tab type now — the panel sits there even
        // when no player is selected, with dash placeholders, so it doesn't pop in
        // and out as the user clicks crew members.
        var showHeight = activeType == DocumentType.Medical || activeType == DocumentType.Security;
        var showWeight = activeType == DocumentType.Medical || activeType == DocumentType.Security;
        var showContact = activeType == DocumentType.Medical;
        var showWorkAuth = activeType == DocumentType.Employment;
        var showIdFeatures = activeType == DocumentType.Security;
        var showAllergies = activeType == DocumentType.Medical;
        var showDrugAllergies = activeType == DocumentType.Medical;
        var showPostmortem = activeType == DocumentType.Medical;

        DocGenHeightLabel.Visible = DocGenHeightValue.Visible = showHeight;
        DocGenWeightLabel.Visible = DocGenWeightValue.Visible = showWeight;
        DocGenContactLabel.Visible = DocGenContactValue.Visible = showContact;
        DocGenWorkAuthLabel.Visible = DocGenWorkAuthValue.Visible = showWorkAuth;
        DocGenIdFeaturesLabel.Visible = DocGenIdFeaturesValue.Visible = showIdFeatures;
        DocGenAllergiesLabel.Visible = DocGenAllergiesValue.Visible = showAllergies;
        DocGenDrugAllergiesLabel.Visible = DocGenDrugAllergiesValue.Visible = showDrugAllergies;
        DocGenPostmortemLabel.Visible = DocGenPostmortemValue.Visible = showPostmortem;

        // Hide the whole panel only when the tab has no general fields at all
        // (CentralCommand / Syndicate / Admin). For Medical / Security / Employment
        // it stays visible so the layout doesn't shift on player select.
        GeneralInfoPanel.Visible = showHeight || showWeight || showContact || showWorkAuth
            || showIdFeatures || showAllergies || showDrugAllergies || showPostmortem;

        // Always populate values — actual data if a player is selected, dashes otherwise.
        DocGenHeightValue.Text = g != null && g.Height > 0 ? $"{g.Height} cm" : "-";
        DocGenWeightValue.Text = g != null && g.Weight > 0 ? $"{g.Weight} kg" : "-";
        DocGenContactValue.Text = g != null && !string.IsNullOrEmpty(g.EmergencyContactName) ? g.EmergencyContactName : "-";
        DocGenWorkAuthValue.Text = g != null
            ? Loc.GetString(g.HasWorkAuthorization ? "sv-document-general-yes" : "sv-document-general-no")
            : "-";
        DocGenIdFeaturesValue.Text = g != null && !string.IsNullOrEmpty(g.IdentifyingFeatures) ? g.IdentifyingFeatures : "-";
        DocGenAllergiesValue.Text = g != null && !string.IsNullOrEmpty(g.Allergies) ? g.Allergies : "-";
        DocGenDrugAllergiesValue.Text = g != null && !string.IsNullOrEmpty(g.DrugAllergies) ? g.DrugAllergies : "-";
        DocGenPostmortemValue.Text = g != null && !string.IsNullOrEmpty(g.PostmortemInstructions) ? g.PostmortemInstructions : "-";
    }

    private void PopulateDocumentListing()
    {
        if (_cachedDocuments == null)
        {
            DocumentListing.Clear();
            return;
        }

        _isPopulating = true;
        DocumentListing.Clear();

        IEnumerable<KeyValuePair<int, CharacterDocument>> rows = _cachedDocuments;
        if (_activeTypeFilter is { } filter)
            rows = rows.Where(kv => kv.Value.DocType == (int) filter);

        foreach (var (_, doc) in rows.OrderBy(x => x.Value.DocTitle))
            DocumentListing.AddItem(doc.DocTitle, null, true, doc.DocID);

        DocumentListingStatus.Visible = false;
        DocumentListing.Visible = true;

        if (_lastSelectedDoc != null)
        {
            _selectedDocument = _lastSelectedDoc;
            for (var i = 0; i < DocumentListing.Count; i++)
            {
                if (DocumentListing[i].Metadata is int docId && docId == _lastSelectedDoc.DocID)
                {
                    DocumentListing[i].Selected = true;
                    break;
                }
            }
        }

        _isPopulating = false;
    }

    private NetEntity _selectedPlayer;
    private Dictionary<NetEntity, string> _cachedPlayerList = new();
    private CharacterDocument? _selectedDocument;
    private bool _confirmingDelete;
    private bool _editing;

    /// <summary>Currently-selected type filter for multi-type consoles. Null = no filter (single-type).</summary>
    private DocumentType? _activeTypeFilter;
    /// <summary>Last received documents, kept to re-filter when the user switches tabs.</summary>
    private Dictionary<int, CharacterDocument>? _cachedDocuments;
    /// <summary>Last selection on the player, for use when tab changes re-populate the listing.</summary>
    private CharacterDocument? _lastSelectedDoc;
    /// <summary>Cached general flavour block for the selected player, kept so tab switches can re-render without a server round-trip.</summary>
    private CharacterDocumentGeneral? _cachedGeneral;
    /// <summary>Console's primary type — used as the fallback active type when no tab strip is shown.</summary>
    private DocumentType _consolePrimaryType;
    public Action<NetEntity>? OnPlayerSelected;
    public Action<NetEntity, int>? OnDocumentSelected;
    public Action<NetEntity, string, DocumentType?>? OnButtonScanPressed;
    public Action<NetEntity, CharacterDocument>? OnButtonPrintPressed;
    public Action<NetEntity, CharacterDocument>? OnButtonDeletePressed;
    public Action<NetEntity, CharacterDocument>? OnButtonEditPressed;
    public Action<NetEntity>? OnStatusButtonPressed;
    public Action? OnDocumentDeselected;
    bool _isPopulating;
}
