using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SV.CharacterDocuments.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDocumentTitlePopup : DefaultWindow
{
    public event Action<string>? OnConfirmed;

    public CharacterDocumentTitlePopup()
    {
        RobustXamlLoader.Load(this);

        OKButton.OnPressed += _ =>
        {
            var title = TitleInput.Text.Trim();
            if (string.IsNullOrEmpty(title))
                return;

            OnConfirmed?.Invoke(title);
            Close();
        };

        CancelButton.OnPressed += _ => Close();

        TitleInput.OnTextEntered += _ =>
        {
            var title = TitleInput.Text.Trim();
            if (string.IsNullOrEmpty(title))
                return;
            OnConfirmed?.Invoke(title);
            Close();
        };
    }
}
