using Content.Shared.Security;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SV.CharacterDocuments.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDocumentStatusPopup : DefaultWindow
{
    public event Action<SecurityStatus, string?>? OnConfirmed;

    private static readonly SecurityStatus[] RequiresReason =
    [
        SecurityStatus.Wanted,
        SecurityStatus.Suspected,
        SecurityStatus.Hostile,
    ];

    private SecurityStatus _selectedStatus = SecurityStatus.None;

    public CharacterDocumentStatusPopup()
    {
        RobustXamlLoader.Load(this);

        foreach (SecurityStatus status in Enum.GetValues<SecurityStatus>())
        {
            StatusPicker.AddItem(status.ToString(), (int)status);
        }

        StatusPicker.OnItemSelected += args =>
        {
            StatusPicker.SelectId(args.Id);
            _selectedStatus = (SecurityStatus)args.Id;
        };

        OKButton.OnPressed += _ =>
        {
            var reason = ReasonInput.Text.Trim();

            if (RequiresReason.Contains(_selectedStatus) && string.IsNullOrEmpty(reason))
                return;

            OnConfirmed?.Invoke(_selectedStatus, string.IsNullOrEmpty(reason) ? null : reason);
            Close();
        };

        CancelButton.OnPressed += _ => Close();
    }
}
