# SPDX-FileCopyrightText: 2026 Cosmatic Drift contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2025 youtissoum <51883137+youtissoum@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: MIT

- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  special:
  - !type:NotifyDepartmentSpecial
    notify_text: job-prisoner-sec-notify-text
    radio_channel: Security

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetGrey

- type: chameleonOutfit
  id: PrisonerChameleonOutfit
  job: Prisoner
