// SPDX-FileCopyrightText: 2026 Moffstation contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 qu4drivium <aaronholiver@outlook.com>
//
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class ForgeSignatureWindow : DefaultWindow
{
    public event Action<string>? OnSignatureChanged;

    private bool _focused;
    private string _signature = string.Empty;

	public ForgeSignatureWindow()
	{
        RobustXamlLoader.Load(this);

        SignatureLineEdit.OnTextChanged += e =>
        {
            _signature = e.Text;
            OnSignatureChanged?.Invoke(_signature);
        };

        SignatureLineEdit.OnFocusEnter += _ => _focused = true;
        SignatureLineEdit.OnFocusExit += _ =>
        {
            _focused = false;
            SignatureLineEdit.Text = _signature;
        };
	}

	public void SetCurrentSignature(string signature)
	{
        if (signature == _signature)
            return;

        _signature = signature;
        if (!_focused)
            SignatureLineEdit.Text = signature;
	}

    public void SetMaxSignatureLength(int maxLength)
    {
        SignatureLineEdit.IsValid = s => s.Length <= maxLength;
    }

}


