// SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Preferences;
using Content.Shared._SV.CharacterDocuments;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SV.CharacterDocuments.Lobby;

/// <summary>
///     Lobby-side editor tab for SV character documents. Reads from
///     <see cref="HumanoidCharacterProfile.SVCharacterDocuments"/> (populated server-side
///     from the persistent SV docs store) and writes edits back through the supplied push
///     action — which round-trips through the existing MsgUpdateCharacter pipeline.
///     Stamps are never edited here; they're preserved server-side when matching DocIDs are found.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SVDocumentEditorGui : Control
{
    private static readonly (DocumentType Type, string LocKey)[] TabTypes =
    {
        (DocumentType.Employment, "sv-document-lobby-tab-employment"),
        (DocumentType.Medical, "sv-document-lobby-tab-medical"),
        (DocumentType.Security, "sv-document-lobby-tab-security"),
        (DocumentType.CentralCommand, "sv-document-lobby-tab-centralcommand"),
        (DocumentType.Syndicate, "sv-document-lobby-tab-syndicate"),
        (DocumentType.Admin, "sv-document-lobby-tab-admin"),
    };

    private readonly Action<List<CharacterDocument>> _push;
    private readonly Action<CharacterDocumentGeneral> _pushGeneral;
    private readonly Dictionary<DocumentType, SVDocumentEntrySelector> _selectors;

    /// <summary>The merged list backing what's currently displayed across all tabs.</summary>
    private List<CharacterDocument> _allDocs = new();

    /// <summary>Used to issue locally-unique negative DocIDs for newly-added docs that the server hasn't assigned yet.</summary>
    private int _nextTempId = -1;

    /// <summary>Character name used as the author fallback when the player leaves the field blank.</summary>
    private string _characterNameFallback = string.Empty;

    /// <summary>Current state of the general flavour block; mutated through With* helpers.</summary>
    private CharacterDocumentGeneral _general = CharacterDocumentGeneral.Default();

    /// <summary>Suppresses change handlers while we set widget values from incoming state.</summary>
    private bool _suppressGeneralEvents;

    public SVDocumentEditorGui(Action<List<CharacterDocument>> push, Action<CharacterDocumentGeneral> pushGeneral)
    {
        RobustXamlLoader.Load(this);
        _push = push;
        _pushGeneral = pushGeneral;

        WireGeneralFields();

        _selectors = new Dictionary<DocumentType, SVDocumentEntrySelector>
        {
            [DocumentType.Employment] = EmploymentSelector,
            [DocumentType.Medical] = MedicalSelector,
            [DocumentType.Security] = SecuritySelector,
            [DocumentType.CentralCommand] = CentralCommandSelector,
            [DocumentType.Syndicate] = SyndicateSelector,
            [DocumentType.Admin] = AdminSelector,
        };

        // Tab 0 is the General tab (added in XAML before the selectors).
        TypeTabs.SetTabTitle(0, Loc.GetString("sv-document-lobby-general-tab-title"));

        for (var i = 0; i < TabTypes.Length; i++)
        {
            var (type, locKey) = TabTypes[i];
            // +1 because the General tab is index 0.
            TypeTabs.SetTabTitle(i + 1, Loc.GetString(locKey));

            // Syndicate and CentralCommand docs are HRP-critical and must be
            // authored in-game (uplink / CentComm consoles) or by admins — never
            // by players in the lobby. Lock down the mutating buttons; players
            // can still see the documents on their character.
            var readOnly = type == DocumentType.Syndicate || type == DocumentType.CentralCommand;
            _selectors[type].Initialize(type, readOnly);

            _selectors[type].OnAdd += (docType, title, author, content) => HandleAdd(docType, title, author, content);
            _selectors[type].OnEdit += (docId, title, author, content) => HandleEdit(docId, title, author, content);
            _selectors[type].OnDelete += docId => HandleDelete(docId);
            _selectors[type].OnReorder += (docId, direction) => HandleReorder(docId, direction);
        }
    }

    public void Update(HumanoidCharacterProfile? profile)
    {
        _characterNameFallback = profile?.Name ?? string.Empty;
        _allDocs = profile?.SVCharacterDocuments == null
            ? new List<CharacterDocument>()
            : profile.SVCharacterDocuments.Select(Clone).ToList();

        // Imported docs all arrive with DocID == 0, and every editor operation (edit, delete,
        // reorder, re-select) keys on DocID — so without unique IDs, deleting one imported doc would nuke them all which is not ideal
        _nextTempId = CharacterDocumentIds.AssignTempIds(_allDocs, _nextTempId);

        _general = profile?.SVCharacterDocumentGeneral == null
            ? CharacterDocumentGeneral.Default()
            : new CharacterDocumentGeneral(profile.SVCharacterDocumentGeneral);

        RefreshAllSelectors();
        RefreshGeneralWidgets();
    }

    private void WireGeneralFields()
    {
        HeightEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            if (int.TryParse(args.Text, out var v))
                PushGeneral(_general.WithHeight(v));
        };
        WeightEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            if (int.TryParse(args.Text, out var v))
                PushGeneral(_general.WithWeight(v));
        };
        EmergencyContactEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            PushGeneral(_general.WithEmergencyContactName(args.Text));
        };
        WorkAuthorizationCheckBox.OnToggled += args =>
        {
            if (_suppressGeneralEvents) return;
            PushGeneral(_general.WithWorkAuthorization(args.Pressed));
        };
        IdentifyingFeaturesEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            PushGeneral(_general.WithIdentifyingFeatures(args.Text));
        };
        AllergiesEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            PushGeneral(_general.WithAllergies(args.Text));
        };
        DrugAllergiesEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            PushGeneral(_general.WithDrugAllergies(args.Text));
        };
        PostmortemEdit.OnTextChanged += args =>
        {
            if (_suppressGeneralEvents) return;
            PushGeneral(_general.WithPostmortemInstructions(args.Text));
        };
    }

    private void RefreshGeneralWidgets()
    {
        _suppressGeneralEvents = true;
        try
        {
            HeightEdit.SetText(_general.Height.ToString());
            WeightEdit.SetText(_general.Weight.ToString());
            EmergencyContactEdit.SetText(_general.EmergencyContactName);
            WorkAuthorizationCheckBox.Pressed = _general.HasWorkAuthorization;
            IdentifyingFeaturesEdit.SetText(_general.IdentifyingFeatures);
            AllergiesEdit.SetText(_general.Allergies);
            DrugAllergiesEdit.SetText(_general.DrugAllergies);
            PostmortemEdit.SetText(_general.PostmortemInstructions);
        }
        finally
        {
            _suppressGeneralEvents = false;
        }
    }

    private void PushGeneral(CharacterDocumentGeneral updated)
    {
        updated.EnsureValid();
        _general = updated;
        _pushGeneral(new CharacterDocumentGeneral(_general));
    }

    private void RefreshAllSelectors()
    {
        foreach (var (type, selector) in _selectors)
        {
            var bucket = _allDocs.Where(d => d.DocType == (int) type).ToList();
            selector.UpdateContents(bucket);
        }
    }

    private void HandleAdd(DocumentType type, string title, string author, string content)
    {
        var resolvedAuthor = string.IsNullOrWhiteSpace(author) ? _characterNameFallback : author.Trim();
        _allDocs.Add(new CharacterDocument
        {
            DocID = _nextTempId--,
            DocType = (int) type,
            DocTitle = string.IsNullOrWhiteSpace(title) ? "Untitled" : title.Trim(),
            DocAuthor = resolvedAuthor,
            DocLastEditedBy = resolvedAuthor,
            DocDateLastEdited = DateTime.Now.AddYears(200),
            DocContent = content ?? string.Empty,
            DocStamps = new List<CharacterDocumentStamp>(),
        });
        Push();
    }

    private void HandleEdit(int docId, string title, string author, string content)
    {
        var target = _allDocs.FirstOrDefault(d => d.DocID == docId);
        if (target == null)
            return;

        var resolvedAuthor = string.IsNullOrWhiteSpace(author) ? _characterNameFallback : author.Trim();
        target.DocTitle = string.IsNullOrWhiteSpace(title) ? target.DocTitle : title.Trim();
        target.DocAuthor = resolvedAuthor;
        target.DocLastEditedBy = resolvedAuthor;
        target.DocContent = content ?? string.Empty;
        target.DocDateLastEdited = DateTime.Now.AddYears(200);
        Push();
    }

    private void HandleDelete(int docId)
    {
        _allDocs.RemoveAll(d => d.DocID == docId);
        Push();
    }

    /// <summary>direction = -1 for up, +1 for down; reorders relative to other docs of the same type.</summary>
    private void HandleReorder(int docId, int direction)
    {
        var idx = _allDocs.FindIndex(d => d.DocID == docId);
        if (idx < 0)
            return;

        // Find neighbouring doc of the same type in the requested direction.
        var type = _allDocs[idx].DocType;
        var step = Math.Sign(direction);
        var i = idx + step;
        while (i >= 0 && i < _allDocs.Count && _allDocs[i].DocType != type)
            i += step;

        if (i < 0 || i >= _allDocs.Count)
            return;

        (_allDocs[idx], _allDocs[i]) = (_allDocs[i], _allDocs[idx]);
        Push();
    }

    private void Push()
    {
        _push(_allDocs.Select(Clone).ToList());
        RefreshAllSelectors();
    }

    private static CharacterDocument Clone(CharacterDocument d) => new()
    {
        DocID = d.DocID,
        DocType = d.DocType,
        DocTitle = d.DocTitle,
        DocAuthor = d.DocAuthor,
        DocLastEditedBy = d.DocLastEditedBy,
        DocDateLastEdited = d.DocDateLastEdited,
        DocContent = d.DocContent,
        DocStamps = new List<CharacterDocumentStamp>(d.DocStamps),
    };
}
