// SPDX-FileCopyrightText: 2026 Sector-Vestige contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._SV.CharacterDocuments;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._SV.CharacterDocuments.Lobby;

[GenerateTypedNameReferences]
public sealed partial class SVDocumentEditPopup : FancyWindow
{
    public const int TitleMaxLen = 64;
    public const int ContentMaxLen = 8192;

    private bool _isValid;
    private DocumentType _docType;

    public SVDocumentEditPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ValidationLabel.FontColorOverride = Color.FromHex("#ff6666");
        ValidationLabel.Visible = false;

        TitleEdit.OnTextChanged += args =>
        {
            if (args.Text.Length > TitleMaxLen)
                TitleEdit.Text = args.Text[..TitleMaxLen];
            ValidateFields();
        };

        AuthorEdit.OnTextChanged += args =>
        {
            if (args.Text.Length > TitleMaxLen)
                AuthorEdit.Text = args.Text[..TitleMaxLen];
            ValidateFields();
        };

        ContentEdit.OnTextChanged += _ => ValidateFields();

        SaveButton.OnPressed += _ =>
        {
            if (!_isValid)
                return;
            Close();
        };
    }

    // Keep the dialog centred as the game window (the UI root) is resized, so it
    // tracks the window instead of being stranded at its original open position.
    protected override void Opened()
    {
        base.Opened();
        var root = UserInterfaceManager.WindowRoot;
        root.OnResized -= RecenterOnRootResize; // idempotent: never stack across reopens
        root.OnResized += RecenterOnRootResize;
    }

    public override void Close()
    {
        UserInterfaceManager.WindowRoot.OnResized -= RecenterOnRootResize;
        base.Close();
    }

    private void RecenterOnRootResize() => RecenterWindow(new Vector2(0.5f, 0.5f));

    private void ValidateFields()
    {
        var contentText = ContentEdit.TextRope == null ? string.Empty : Rope.Collapse(ContentEdit.TextRope);

        if (string.IsNullOrWhiteSpace(TitleEdit.Text))
        {
            ValidationLabel.Text = Loc.GetString("sv-document-lobby-edit-popup-title-required");
            ValidationLabel.Visible = true;
            _isValid = false;
        }
        else if (string.IsNullOrWhiteSpace(contentText))
        {
            ValidationLabel.Text = Loc.GetString("sv-document-lobby-edit-popup-content-required");
            ValidationLabel.Visible = true;
            _isValid = false;
        }
        else if (contentText.Length > ContentMaxLen)
        {
            ValidationLabel.Text = Loc.GetString(
                "sv-document-lobby-edit-popup-content-too-long",
                ("current", contentText.Length),
                ("max", ContentMaxLen));
            ValidationLabel.Visible = true;
            _isValid = false;
        }
        else
        {
            ValidationLabel.Visible = false;
            _isValid = true;
        }

        SaveButton.Disabled = !_isValid;
    }

    public (string Title, string Author, string Content) GetContents()
    {
        var content = ContentEdit.TextRope == null ? string.Empty : Rope.Collapse(ContentEdit.TextRope).Trim();
        return (TitleEdit.Text.Trim(), AuthorEdit.Text.Trim(), content);
    }

    public void SetContents(DocumentType docType, CharacterDocument doc)
    {
        _docType = docType;
        TitleEdit.Text = doc.DocTitle;
        AuthorEdit.Text = doc.DocAuthor;
        ContentEdit.TextRope = new Rope.Leaf(doc.DocContent);
        ValidateFields();
    }
}
