using System.Linq;
using Content.Client.Paper.UI;
using Content.Shared._SV.CharacterDocuments;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SV.CharacterDocuments.Lobby;

/// <summary>
///     One tab in the SV documents lobby editor — shows entries for a single DocumentType
///     and emits add/edit/delete/reorder intents to the parent. Holds no authoritative state;
///     all data flows down from the GUI's snapshot.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SVDocumentEntrySelector : Control
{
    public event Action<DocumentType, string, string, string>? OnAdd;
    public event Action<int, string, string, string>? OnEdit;
    public event Action<int>? OnDelete;
    public event Action<int, int>? OnReorder; // (docId, direction) — direction is -1 or +1

    private DocumentType _docType;
    private List<CharacterDocument> _entries = new();
    private readonly SVDocumentEditPopup _editPopup = new();
    private int? _editingDocId; // null = creating, set = editing this DocID

    public SVDocumentEntrySelector()
    {
        RobustXamlLoader.Load(this);

        EntrySelector.OnItemSelected += args => ShowPreview(args.ItemIndex);
        EntrySelector.OnItemDeselected += _ => ClearPreview();

        AddButton.OnPressed += _ =>
        {
            _editingDocId = null;
            _editPopup.SetContents(_docType, new CharacterDocument
            {
                DocType = (int) _docType,
                DocTitle = string.Empty,
                DocAuthor = string.Empty,
                DocContent = string.Empty,
                DocStamps = new List<CharacterDocumentStamp>(),
            });
            _editPopup.Open();
        };

        EditButton.OnPressed += _ =>
        {
            if (!EntrySelector.GetSelected().Any())
                return;
            var idx = EntrySelector.IndexOf(EntrySelector.GetSelected().First());
            if (idx < 0 || idx >= _entries.Count)
                return;
            _editingDocId = _entries[idx].DocID;
            _editPopup.SetContents(_docType, _entries[idx]);
            _editPopup.Open();
        };

        RemoveButton.OnPressed += _ =>
        {
            if (!EntrySelector.GetSelected().Any())
                return;
            var idx = EntrySelector.IndexOf(EntrySelector.GetSelected().First());
            if (idx < 0 || idx >= _entries.Count)
                return;
            ClearPreview();
            OnDelete?.Invoke(_entries[idx].DocID);
        };

        UpButton.OnPressed += _ =>
        {
            if (!EntrySelector.GetSelected().Any())
                return;
            var idx = EntrySelector.IndexOf(EntrySelector.GetSelected().First());
            if (idx < 0 || idx >= _entries.Count)
                return;
            OnReorder?.Invoke(_entries[idx].DocID, -1);
        };

        DownButton.OnPressed += _ =>
        {
            if (!EntrySelector.GetSelected().Any())
                return;
            var idx = EntrySelector.IndexOf(EntrySelector.GetSelected().First());
            if (idx < 0 || idx >= _entries.Count)
                return;
            OnReorder?.Invoke(_entries[idx].DocID, +1);
        };

        _editPopup.SaveButton.OnPressed += _ =>
        {
            var (title, author, content) = _editPopup.GetContents();
            if (_editingDocId is { } id)
                OnEdit?.Invoke(id, title, author, content);
            else
                OnAdd?.Invoke(_docType, title, author, content);
        };

        OnVisibilityChanged += _ => _editPopup.Close();
    }

    public void Initialize(DocumentType docType, bool readOnly = false)
    {
        _docType = docType;

        // Read-only tabs (Syndicate / CentralCommand) lock down all mutating buttons.
        // Players can still SELECT entries to preview them — they just can't add,
        // edit, delete, or reorder. Those types must be authored in-game (uplink
        // scans, CentComm consoles) or by an admin via the admin browser EUI.
        if (readOnly)
        {
            AddButton.Disabled = true;
            EditButton.Disabled = true;
            RemoveButton.Disabled = true;
            UpButton.Disabled = true;
            DownButton.Disabled = true;
        }
    }

    public void UpdateContents(List<CharacterDocument> entries)
    {
        // Remember which doc was selected so we can re-show it after the rebuild.
        // Without this, saving an edit blanks the preview pane (and the user can't
        // see their new copy until they re-click the entry).
        int? selectedDocId = null;
        if (EntrySelector.GetSelected().Any())
        {
            var prevIdx = EntrySelector.IndexOf(EntrySelector.GetSelected().First());
            if (prevIdx >= 0 && prevIdx < _entries.Count)
                selectedDocId = _entries[prevIdx].DocID;
        }

        _entries = entries;
        EntrySelector.Clear();
        foreach (var entry in _entries)
            EntrySelector.AddItem(entry.DocTitle);

        var reselect = selectedDocId is { } id ? _entries.FindIndex(d => d.DocID == id) : -1;
        if (reselect >= 0)
        {
            EntrySelector[reselect].Selected = true;
            ShowPreview(reselect);
        }
        else
        {
            ClearPreview();
        }
    }

    private void ShowPreview(int idx)
    {
        if (idx < 0 || idx >= _entries.Count)
        {
            ClearPreview();
            return;
        }

        var doc = _entries[idx];
        PreviewTitleLabel.Text = string.IsNullOrWhiteSpace(doc.DocTitle)
            ? Loc.GetString("sv-document-lobby-preview-empty")
            : doc.DocTitle;
        PreviewAuthorLabel.Text = string.IsNullOrWhiteSpace(doc.DocAuthor)
            ? Loc.GetString("sv-document-lobby-preview-author-default")
            : doc.DocAuthor;
        PreviewContent.SetDocumentContent(doc.DocContent);

        // Stamps are display-only here; lobby never edits them.
        PreviewStamps.RemoveStamps();
        PreviewStamps.RemoveAllChildren();
        foreach (var stamp in doc.DocStamps)
            PreviewStamps.AddStamp(new StampWidget { StampInfo = stamp.DocStamp });
    }

    private void ClearPreview()
    {
        PreviewTitleLabel.Text = Loc.GetString("sv-document-lobby-preview-empty");
        PreviewAuthorLabel.Text = string.Empty;
        PreviewContent.Text = null;
        PreviewStamps.RemoveStamps();
        PreviewStamps.RemoveAllChildren();
    }
}
