using Content.Shared._SV.Delivery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SV.Delivery.UI;

/// <summary>
/// Window for addressing a letter to a crewmember. Renders the station crew as a selectable list
/// and lets the player send the addressed letter through the mail system.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AddressableDeliveryWindow : DefaultWindow
{
    /// <summary>
    /// Raised with the selected station record id when the player picks a recipient.
    /// </summary>
    public event Action<uint>? OnRecipientSelected;

    /// <summary>
    /// Raised when the player presses the send button.
    /// </summary>
    public event Action? OnSendPressed;

    private bool _populating;

    public AddressableDeliveryWindow()
    {
        RobustXamlLoader.Load(this);

        CrewList.OnItemSelected += args =>
        {
            if (_populating || CrewList[args.ItemIndex].Metadata is not uint id)
                return;

            OnRecipientSelected?.Invoke(id);
        };

        SendButton.OnPressed += _ => OnSendPressed?.Invoke();
    }

    public void UpdateState(AddressableDeliveryBuiState state)
    {
        _populating = true;

        CrewList.Clear();
        CrewList.ClearSelected();

        EmptyLabel.Visible = state.Crew.Count == 0;
        CrewList.Visible = state.Crew.Count != 0;

        foreach (var (id, label) in state.Crew)
        {
            var item = CrewList.AddItem(label);
            item.Metadata = id;
            item.Selected = state.SelectedKey == id;
        }

        CrewList.SortItemsByText();

        SendButton.Disabled = state.SelectedKey == null;

        _populating = false;
    }
}
