// SPDX-FileCopyrightText: 2026 Cosmatic Drift contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Admin.UI;

[GenerateTypedNameReferences]
public sealed partial class ModifyCharacterRecords : DefaultWindow
{
    public ModifyCharacterRecords()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var v in Enum.GetValues<CharacterRecordType>())
        {
            EntityEntryType.AddItem(v.ToString());
        }

        EntityEntryType.OnItemSelected += args =>
        {
            EntityEntryType.SelectId(args.Id);
            UpdateCommands();
        };

        EntityEdit.OnTextChanged += _ => UpdateCommands();
        EntityEntryIndex.OnTextChanged += _ => UpdateCommands();
    }

    private void UpdateCommands()
    {
        if (!int.TryParse(EntityEdit.Text, out var uid))
        {
            return;
        }

        if (!int.TryParse(EntityEntryIndex.Text, out var idx))
        {
            return;
        }

        var ty = (CharacterRecordType)EntityEntryType.SelectedId;

        PurgeCommand.Command = $"purgecharacterrecords {uid}";
        DelCommand.Command = $"delrecordentry {uid} {ty.ToString()} {idx}";
    }
}
