# SPDX-FileCopyrightText: 2026 Delta-V contributors
# SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2024 V <97265903+formlessnameless@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

#Misc outfit startingGear definitions.

- type: startingGear
  id: SyndicateListenerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateBlack
    head: ClothingHeadPyjamaSyndicateBlack
    ears: ClothingHeadsetAltSyndicateListening
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesSlippers
    id: SyndiListeningPostPDA
#  innerClothingSkirt: ClothingUniformJumpsuitPyjamaSyndicatePink # I don't think loadouts work for ghost roles anyways
